sudo: false
language: python
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pytest pytest_cov==2.6.0 codecov

script:
  - python -m pytest --cov=numerai_reports

after_success:
  - codecov
